# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='parts',
        ),
        migrations.AddField(
            model_name='invoice',
            name='parts',
            field=models.ManyToManyField(related_name='parts', to='system.Parts'),
        ),
    ]
