# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20160209_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='tyre_id',
        ),
        migrations.DeleteModel(
            name='Tyres',
        ),
    ]
